import { createContext, useState, useCallback, useMemo, type ReactNode } from "react";

export type Lang = "zh" | "en";

export interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextValue | null>(null);

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    "app.title": "SynthMind",
    "app.settings": "Settings",
    "settings.providers": "Providers",
    "settings.skills": "Skills",
    "settings.memory": "Memory",
    "settings.feishu": "Feishu",
    "settings.whitelist": "Whitelist",
    "settings.traces": "Traces",
    "settings.appearance": "Appearance",
    "settings.close": "Close",
    "feishu.title": "Feishu Bot Configuration",
    "feishu.loading": "Loading...",
    "feishu.app_id": "App ID",
    "feishu.app_secret": "App Secret",
    "feishu.bot_name": "Bot Name",
    "feishu.bot_name_hint": "(for @mention in groups)",
    "feishu.app_id_placeholder": "cli_xxxxxxxxxxxxx",
    "feishu.app_secret_placeholder": "Enter your app secret",
    "feishu.save": "Save",
    "feishu.saving": "Saving...",
    "feishu.saved": "Configuration saved! Restart the backend to apply changes.",
    "feishu.save_failed": "Save failed:",
    "feishu.hint": "After saving, restart the backend to apply changes. Make sure your Feishu app has:",
    "feishu.hint_robot": "- 机器人 capability enabled",
    "feishu.hint_permission": "- im:message permission",
    "feishu.hint_event": "- im.message.receive_v1 event subscribed",
    "feishu.hint_ws": "- WebSocket mode (长连接)",
    "providers.title": "Configured Models",
    "providers.empty": "No configurations yet.",
    "providers.add": "+ Add",
    "providers.edit": "Edit",
    "providers.delete": "Del",
    "providers.cancel": "Cancel",
    "providers.test": "Test",
    "providers.testing": "Testing...",
    "providers.name": "Display Name",
    "providers.name_placeholder": "e.g. My Model",
    "providers.provider": "Provider",
    "providers.model": "Model",
    "providers.model_placeholder": "e.g. deepseek-chat",
    "providers.api_key": "API Key",
    "providers.api_key_placeholder": "sk-...",
    "providers.base_url": "Base URL",
    "providers.base_url_hint": "(optional)",
    "providers.base_url_placeholder": "https://api.openai.com/v1",
    "providers.add_title": "Add Model",
    "providers.edit_title": "Edit Model",
    "providers.save": "Save",
    "providers.saving": "Saving...",
    "providers.delete_confirm": "Delete?",
    "providers.save_failed": "Save failed:",
    "skills.title": "Installed Skills",
    "skills.empty": "No skills installed.",
    "skills.new": "+ New",
    "skills.name": "Name",
    "skills.description": "Description",
    "skills.instructions": "Instructions",
    "skills.instructions_placeholder": "Instructions for the agent...",
    "skills.create": "Create",
    "skills.creating": "Creating...",
    "skills.delete_confirm": "Delete skill \"{name}\"?",
    "skills.install_url": "Install from URL",
    "skills.url_placeholder": "https://raw.githubusercontent.com/...",
    "skills.install": "Install",
    "skills.installing": "Installing...",
    "skills.detail_hint": "Click a skill to see details.",
    "memory.title": "All Memories ({count})",
    "memory.add": "+ Add",
    "memory.empty": "No memories yet. The agent will save observations during conversation.",
    "memory.loading": "Loading...",
    "memory.type": "Type",
    "memory.content": "Content",
    "memory.content_placeholder": "What did you learn?",
    "memory.tags": "tags (comma-separated)",
    "memory.save": "Save",
    "memory.filter_all": "All",
    "whitelist.title": "Whitelisted Tools ({count})",
    "whitelist.empty": "No tools whitelisted yet. When a tool requires approval, use Approve &amp; Whitelist to skip future approval prompts for that tool.",
    "whitelist.remove": "Remove",
    "appearance.theme": "Color Theme",
    "appearance.theme_label": "Theme",
    "appearance.font": "Interface Font",
    "appearance.font_label": "Font",
    "appearance.dark": "Dark",
    "appearance.light": "Light",
    "appearance.oled": "OLED Dark (pure black)",
    "appearance.sepia": "Sepia (warm)",
    "appearance.font_inter": "Inter",
    "appearance.font_system": "System Default",
    "appearance.font_serif": "Serif (Georgia)",
    "appearance.font_mono": "Monospace",
    "appearance.font_pingfang": "PingFang SC (中文)",
    "appearance.font_rounded": "Rounded",
    "appearance.font_emoji": "Emoji",
    "appearance.lang": "Language / 语言",
    "appearance.lang_label": "Language",
    "appearance.lang_en": "English",
    "appearance.lang_zh": "中文",
    "appearance.switch_to_light": "Switch to light theme",
    "appearance.switch_to_dark": "Switch to dark theme",
    "chat.placeholder": "Type your message... (Shift+Enter for new line)",
    "chat.send": "Send",
    "chat.thinking": "Thinking...",
    "chat.greeting": "Hello! I'm SynthMind. Choose a model in the sidebar and start chatting.",
    "chat.error": "Error: {msg}",
    "chat.time_travel": "Time Travel — browse execution history and branch",
    "chat.new_session": "Hello! What can I help you with today?",
    "approval.requires": "Tool requires approval",
    "approval.requires_multi": "Tools require approval ({current}/{total})",
    "approval.approve": "Approve",
    "approval.approve_with_whitelist": "Whitelist",
    "approval.reject": "Reject",
    "approval.approve_all": "Approve All ({count})",
    "approval.reject_all": "Reject All",
    "approval.approved": "✅ Approved",
    "approval.rejected": "✕ Rejected",
    "approval.approve_single": "Approve ({current})",
    "threads.title": "Conversations",
    "threads.new": "+ New",
    "threads.empty": "No conversations yet. Create one to start chatting.",
    "threads.workdir": "Working Directory",
    "threads.set_workdir": "Set",
    "threads.edit_workdir": "Edit",
    "threads.browse": "Browse",
    "threads.cancel": "Cancel",
    "threads.clear": "Clear",
    "threads.loading": "Loading...",
    "threads.empty_new": "New conversation",
    "threads.msgs": "msgs",
    "threads.just_now": "just now",
    "threads.min_ago": "{n}m ago",
    "threads.hour_ago": "{n}h ago",
    "threads.day_ago": "{n}d ago",
    "model.provider": "LLM Provider",
    "model.model": "Model",
    "model.reasoning": "Reasoning Effort",
    "model.reasoning_low": "Low",
    "model.reasoning_medium": "Medium",
    "model.reasoning_high": "High",
    "panel.files": "Files",
    "panel.git": "Changes",
    "panel.sandbox": "Sandbox",
    "panel.agents": "Agents",
    "panel.traces": "Traces",
    "files.title": "Workspace",
    "files.loading": "Loading...",
    "files.empty": "Set a working directory in the sidebar to browse files.",
    "files.empty_dir": "(empty)",
    "files.edit": "Edit",
    "files.save": "Save",
    "files.saving": "Saving...",
    "files.cancel": "Cancel",
    "files.fim": "FIM",
    "files.fim_title": "Ctrl+Space: AI code completion",
    "files.commit": "Commit",
    "files.commit_placeholder": "Commit message",
    "files.switch_branch": "Switch branch",
    "git.changes": "Changes",
    "git.log": "Log",
    "git.branches": "Branches",
    "git.commit": "Commit",
    "git.commit_placeholder": "Commit message",
    "git.author_placeholder": "Author (optional)",
    "git.pull": "Pull",
    "git.push": "Push",
    "git.fetch": "Fetch",
    "git.stash": "Stash",
    "git.stage": "Stage",
    "git.unstage": "Unstage",
    "git.discard": "Discard",
    "git.discard_confirm": "Discard changes in {file}?",
    "git.staged": "Staged",
    "git.modified": "Modified",
    "git.untracked": "Untracked",
    "git.conflicted": "Conflicted",
    "git.no_changes": "No changes",
    "git.loading": "Loading...",
    "git.console": "Console",
    "git.clear": "Clear",
    "git.merge": "Merge",
    "git.create": "Create branch",
    "git.filter": "Filter branches...",
    "git.new_branch": "New branch name",
    "git.compare": "Compare",
    "git.current_branch": "Current branch",
    "git.commit_failed": "Commit failed: {msg}",
    "git.checkout_failed": "Checkout failed: {msg}",
    "git.merge_confirm": "Merge {source} into {target}?",
    "diff.loading": "Loading diff...",
    "diff.error": "Error loading diff",
    "branch.from": "From branch",
    "branch.base": "Base branch",
    "branch.target": "Target (optional)",
    "log.loading": "Loading...",
    "log.more": "Load more...",
    "agents.title": "Sub-Agents",
    "agents.empty": "No agents defined yet.",
    "agents.run": "Run",
    "agents.edit": "Edit",
    "agents.delete": "Delete",
    "agents.create": "Create Agent",
    "agents.run_title": "Run Agent",
    "sandbox.title": "Execution History",
    "todo.title": "Tasks",
    "todo.empty": "No pending tasks. Ask the agent to create one.",
    "todo.completed_placeholder": "Completed ({n})",
    "todo.add": "+ Add",
    "todo.placeholder": "Add a task...",
    "todo.toggle_hint": "Click to toggle complete",
    "memory_user": "User",
    "memory_feedback": "Feedback",
    "memory_project": "Project",
    "memory_reference": "Reference",
    "balance.title": "Balance",
    "tt.title": "Time Travel",
    "tt.refresh": "Refresh",
    "tt.loading": "Loading checkpoints...",
    "tt.empty": "No checkpoints found. The checkpointer records snapshots during each agent execution.",
    "tt.branch": "Branch",
    "tt.branch_placeholder": "Message for branched thread...",
    "tt.step": "Step {n}",
    "tt.next": "→ {next}",
    "tt.messages": "{n} messages",
    "tt.branch_failed": "Branch failed: {msg}",
    "traces.title": "LLM & Tool Traces",
    "traces.clear": "Clear All",
    "traces.empty": "No traces yet. Start chatting to see traces.",
    "traces.filter_all": "All",
    "traces.filter_llm": "LLM",
    "traces.filter_tool": "Tool",
    "traces.filter_error": "Error",
    "traces.input": "Input",
    "traces.output": "Output",
    "traces.tokens": "Tokens",
    "traces.latency": "Latency",
    "traces.error": "Error",
    "status.idle": "Idle",
    "status.thinking": "Thinking...",
    "status.error": "Error",
  },
  zh: {
    "app.title": "SynthMind",
    "app.settings": "设置",
    "settings.providers": "模型配置",
    "settings.skills": "技能",
    "settings.memory": "记忆",
    "settings.feishu": "飞书",
    "settings.whitelist": "白名单",
    "settings.traces": "追踪",
    "settings.appearance": "外观",
    "settings.close": "关闭",
    "feishu.title": "飞书机器人配置",
    "feishu.loading": "加载中...",
    "feishu.app_id": "App ID",
    "feishu.app_secret": "App Secret",
    "feishu.bot_name": "机器人名称",
    "feishu.bot_name_hint": "（用于群聊 @ 提及）",
    "feishu.app_id_placeholder": "cli_xxxxxxxxxxxxx",
    "feishu.app_secret_placeholder": "输入你的 App Secret",
    "feishu.save": "保存",
    "feishu.saving": "保存中...",
    "feishu.saved": "配置已保存！重启后端后生效。",
    "feishu.save_failed": "保存失败：",
    "feishu.hint": "保存后重启后端生效。确保飞书应用已配置：",
    "feishu.hint_robot": "- ✅ 启用机器人能力",
    "feishu.hint_permission": "- ✅ im:message 权限",
    "feishu.hint_event": "- ✅ 订阅 im.message.receive_v1 事件",
    "feishu.hint_ws": "- ✅ WebSocket 长连接模式",
    "providers.title": "已配置的模型",
    "providers.empty": "暂无配置。",
    "providers.add": "+ 添加",
    "providers.edit": "编辑",
    "providers.delete": "删除",
    "providers.cancel": "取消",
    "providers.test": "测试连接",
    "providers.testing": "测试中...",
    "providers.name": "显示名称",
    "providers.name_placeholder": "例如：我的模型",
    "providers.provider": "提供商",
    "providers.model": "模型名称",
    "providers.model_placeholder": "例如：deepseek-chat",
    "providers.api_key": "API 密钥",
    "providers.api_key_placeholder": "sk-...",
    "providers.base_url": "接口地址",
    "providers.base_url_hint": "（可选）",
    "providers.base_url_placeholder": "https://api.openai.com/v1",
    "providers.add_title": "添加模型",
    "providers.edit_title": "编辑模型",
    "providers.save": "保存",
    "providers.saving": "保存中...",
    "providers.delete_confirm": "确定删除？",
    "providers.save_failed": "保存失败：",
    "skills.title": "已安装的技能",
    "skills.empty": "暂未安装技能。",
    "skills.new": "+ 新建",
    "skills.name": "名称",
    "skills.description": "描述",
    "skills.instructions": "指令",
    "skills.instructions_placeholder": "给 Agent 的指令...",
    "skills.create": "创建",
    "skills.creating": "创建中...",
    "skills.delete_confirm": "确定删除技能 \"{name}\"？",
    "skills.install_url": "从 URL 安装",
    "skills.url_placeholder": "https://raw.githubusercontent.com/...",
    "skills.install": "安装",
    "skills.installing": "安装中...",
    "skills.detail_hint": "点击技能查看详情。",
    "memory.title": "所有记忆（{count}条）",
    "memory.add": "+ 添加",
    "memory.empty": "暂无记忆。Agent 会在对话中自动保存观察结果。",
    "memory.loading": "加载中...",
    "memory.type": "类型",
    "memory.content": "内容",
    "memory.content_placeholder": "你学到了什么？",
    "memory.tags": "标签（逗号分隔）",
    "memory.save": "保存",
    "memory.filter_all": "全部",
    "whitelist.title": "白名单工具（{count}个）",
    "whitelist.empty": "暂无白名单工具。当审批时选择「Whitelist」可将工具加入白名单，跳过后续审批。",
    "whitelist.remove": "移除",
    "appearance.theme": "颜色主题",
    "appearance.theme_label": "主题",
    "appearance.font": "界面字体",
    "appearance.font_label": "字体",
    "appearance.dark": "深色",
    "appearance.light": "浅色",
    "appearance.oled": "OLED 纯黑",
    "appearance.sepia": "暖黄（阅读）",
    "appearance.font_inter": "Inter",
    "appearance.font_system": "系统默认",
    "appearance.font_serif": "衬线（Georgia）",
    "appearance.font_mono": "等宽",
    "appearance.font_pingfang": "苹方（PingFang SC）",
    "appearance.font_rounded": "圆体",
    "appearance.font_emoji": "Emoji",
    "appearance.lang": "语言 / Language",
    "appearance.lang_label": "语言",
    "appearance.lang_en": "English",
    "appearance.lang_zh": "中文",
    "appearance.switch_to_light": "切换到浅色主题",
    "appearance.switch_to_dark": "切换到深色主题",
    "chat.placeholder": "输入消息...（Shift+Enter 换行）",
    "chat.send": "发送",
    "chat.thinking": "思考中...",
    "chat.greeting": "你好！我是 SynthMind。请在侧边栏选择模型后开始对话。",
    "chat.error": "错误：{msg}",
    "chat.time_travel": "浏览执行历史和分支",
    "chat.new_session": "你好！有什么可以帮助你的吗？",
    "approval.requires": "需要审批",
    "approval.requires_multi": "需要审批（{current}/{total}）",
    "approval.approve": "✅ 批准",
    "approval.approve_with_whitelist": "✅ 批准并加入白名单",
    "approval.reject": "✕ 拒绝",
    "approval.approve_all": "✅ 全部批准（{count}个）",
    "approval.reject_all": "✕ 全部拒绝",
    "approval.approved": "✅ 已批准",
    "approval.rejected": "✕ 已拒绝",
    "approval.approve_single": "✅ 批准（第{current}个）",
    "threads.title": "会话列表",
    "threads.new": "+ 新建",
    "threads.empty": "暂无会话。创建一个开始聊天。",
    "threads.workdir": "工作目录",
    "threads.set_workdir": "设置",
    "threads.edit_workdir": "编辑",
    "threads.browse": "浏览",
    "threads.cancel": "取消",
    "threads.clear": "清除",
    "threads.loading": "加载中...",
    "threads.empty_new": "新会话",
    "threads.msgs": "条消息",
    "threads.just_now": "刚刚",
    "threads.min_ago": "{n}分钟前",
    "threads.hour_ago": "{n}小时前",
    "threads.day_ago": "{n}天前",
    "model.provider": "LLM 提供商",
    "model.model": "模型",
    "model.reasoning": "思考强度",
    "model.reasoning_low": "低",
    "model.reasoning_medium": "中",
    "model.reasoning_high": "高",
    "panel.files": "文件",
    "panel.git": "Git",
    "panel.sandbox": "沙箱",
    "panel.agents": "子代理",
    "panel.traces": "追踪",
    "files.title": "工作空间",
    "files.loading": "加载中...",
    "files.empty": "在侧边栏设置工作目录后可浏览文件。",
    "files.empty_dir": "（空）",
    "files.edit": "编辑",
    "files.save": "保存",
    "files.saving": "保存中...",
    "files.cancel": "取消",
    "files.fim": "FIM",
    "files.fim_title": "Ctrl+Space：AI 代码补全",
    "files.commit": "提交",
    "files.commit_placeholder": "提交信息",
    "files.switch_branch": "切换分支",
    "git.changes": "变更",
    "git.log": "日志",
    "git.branches": "分支",
    "git.commit": "提交",
    "git.commit_placeholder": "提交信息",
    "git.author_placeholder": "作者（可选）",
    "git.pull": "拉取",
    "git.push": "推送",
    "git.fetch": "获取",
    "git.stash": "暂存",
    "git.stage": "暂存",
    "git.unstage": "取消暂存",
    "git.discard": "丢弃",
    "git.discard_confirm": "确定丢弃 {file} 的更改？",
    "git.staged": "已暂存",
    "git.modified": "已修改",
    "git.untracked": "未跟踪",
    "git.conflicted": "冲突",
    "git.no_changes": "无变更",
    "git.loading": "加载中...",
    "git.console": "控制台",
    "git.clear": "清空",
    "git.merge": "合并",
    "git.create": "创建分支",
    "git.filter": "筛选分支...",
    "git.new_branch": "新分支名称",
    "git.compare": "对比",
    "git.current_branch": "当前分支",
    "git.commit_failed": "提交失败：{msg}",
    "git.checkout_failed": "切换失败：{msg}",
    "git.merge_confirm": "将 {source} 合并到 {target}？",
    "diff.loading": "加载 Diff...",
    "diff.error": "Diff 加载失败",
    "branch.from": "来源分支",
    "branch.base": "基准分支",
    "branch.target": "目标分支（可选）",
    "log.loading": "加载中...",
    "log.more": "加载更多...",
    "agents.title": "子代理",
    "agents.empty": "暂未定义子代理。",
    "agents.run": "运行",
    "agents.edit": "编辑",
    "agents.delete": "删除",
    "agents.create": "创建子代理",
    "agents.run_title": "运行子代理",
    "sandbox.title": "执行历史",
    "todo.title": "待办",
    "todo.empty": "暂无待办。让 Agent 创建一个。",
    "todo.completed_placeholder": "已完成 ({n})",
    "todo.add": "+ 添加",
    "todo.placeholder": "添加任务...",
    "todo.toggle_hint": "点击切换完成状态",
    "memory_user": "用户",
    "memory_feedback": "反馈",
    "memory_project": "项目",
    "memory_reference": "参考",
    "balance.title": "余额",
    "tt.title": "Time Travel",
    "tt.refresh": "刷新",
    "tt.loading": "加载检查点...",
    "tt.empty": "暂无检查点。Agent 每次执行时 Checkpointer 会自动记录快照。",
    "tt.branch": "分支",
    "tt.branch_placeholder": "分支线程的消息...",
    "tt.step": "步骤 {n}",
    "tt.next": "→ {next}",
    "tt.messages": "{n} 条消息",
    "tt.branch_failed": "分支创建失败：{msg}",
    "traces.title": "LLM 与工具追踪",
    "traces.clear": "清空全部",
    "traces.empty": "暂无追踪。开始聊天后可查看。",
    "traces.filter_all": "全部",
    "traces.filter_llm": "LLM 调用",
    "traces.filter_tool": "工具调用",
    "traces.filter_error": "错误",
    "traces.input": "输入",
    "traces.output": "输出",
    "traces.tokens": "Token 数",
    "traces.latency": "延迟",
    "traces.error": "错误",
    "status.idle": "就绪",
    "status.thinking": "思考中...",
    "status.error": "错误",
  },
};

function getInitialLang(): Lang {
  try {
    const saved = localStorage.getItem("synthmind_lang");
    if (saved === "zh" || saved === "en") return saved;
  } catch { /* ignore */ }
  const navLang = navigator.language || "";
  if (navLang.startsWith("zh")) return "zh";
  return "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(getInitialLang);

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem("synthmind_lang", l); } catch { /* ignore */ }
  };

  const t = useCallback((key: string): string => {
    const dict = TRANSLATIONS[lang];
    if (key in dict) return dict[key];
    const enDict = TRANSLATIONS.en;
    return enDict[key] || key;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
